### ISSUE TITLE
运行python proxyspider.py出现问题

### ISSUE THREAD

**Issue by sbbbsbbb** [zhangchenchen/proxyspider#2]
root@instance-1:~/proxyspider# python proxyspider.py
Traceback (most recent call last):
  File "proxyspider.py", line 11, in <module>
    from lxml import etree
ImportError: No module named lxml

**Comment by sbbbsbbb** [comment]
已经 pip install lxml

**Comment by zhangchenchen** [comment]
应该是运行环境的事，你可以用virtualenv 建一个虚拟python环境，然后activate之后，在这个虚拟环境中运行~

**Comment by sbbbsbbb** [comment]
嗯， 解决了 非常感谢
